{% set data = load_setup_py_data('../pyproject.toml', from_recipe_dir=True) %}

package:
  name: calsim-dash-widgets
  version: {{ data['project']['version'] }}

source:
  path: ..

build:
  # If the installation is complex, or different between Unix and Windows, use
  # separate bld.bat and build.sh files instead of this key.  Add the line
  # "skip: True  # [py<35]" (for example) to limit to Python 3.5 and newer, or
  # "skip: True  # [not win]" to limit to Windows.
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"
  noarch: python
  
  
requirements:
  # if you need compilers, uncomment these
  #    read more at https://docs.conda.io/projects/conda-build/en/latest/resources/compiler-tools.html
  # build:
  #   - {{ compilers('c') }}
  host:
    - python
    - pip
  run:
    - python
    # dependencies are defined in setup.py
    {% for dep in data['project']['dependencies'] %}
    - {{ dep.lower() }}
    {% endfor %}

test:
  source_files:
    - tests

about:
  home: https://github.com/CentralValleyModeling/calsim-dash-widgets
  summary: Common widgets for plotly-dash based CalSim dashboards.
  license: {{ data.get('license') }}
  license_file: LICENSE
